[substrate] remove pullSecret from charts
inteli-poc/bevel pull request #50
Opened 2022-07-19 11:52 UTC by TonyRowntree

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>

**Changelog**
- Removed pullSecret key from charts

tested on uat-network

 
 

**Linked issue**
#INFRA-139

2022-07-19 12:37 UTC, sownak requested changes

2022-07-19 12:37 UTC, sownak commented on examples/dscp-app/charts/dscp-api/templates/_helpers.tpl
> -
This part is fine, no need to remove

2022-07-19 12:37 UTC, sownak commented on examples/dscp-app/charts/inteli-api/values.yaml
> -  pullSecrets: ['ghcr-digicatapult']
only remove the value here

2022-07-19 12:37 UTC, sownak commented on platforms/substrate/charts/substrate-node/values.yaml
> -imagePullSecrets: []
this need not be removed

2022-07-19 12:47 UTC, sownak approved these changes

2022-07-19 12:57 UTC, merged

2022-07-22 18:48 UTC, dblane-digicatapult commented
Hi,

I think if you are removing the pullSecrets then you should switch to using the containers on dockerhub. As far as I know ghcr still requires auth.