#INFRA-45 Create helm template for deploying VITALam IPFS node
inteli-poc/bevel pull request #6
Opened 2022-02-14 15:01 UTC by TonyRowntree

**Changelog**
- Added the helm release template for VITALam ipfs node

 

**Reviewed by**

 

**Linked issue**
#INFRA-45

depends on #4

2022-02-14 15:32 UTC, TonyRowntree commented
@sownak might want to hold back on merging this as some changes to digi's ipfs chart are imminent - will re-request review when the changes have been made.

2022-02-14 15:44 UTC, sownak requested changes

2022-02-14 15:44 UTC, sownak commented on platforms/substrate/configuration/roles/create/helm_component/vars/main.yaml
> +  vitalam_ipfs_job: vitalam_ipfs_job.tpl
rename this, it is not a job.

2022-02-15 12:55 UTC, sownak approved these changes

2022-02-15 12:55 UTC, merged